name: lazy_fit
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  go_router: ^14.1.4
  video_player: ^2.8.7
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/buttons/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Medium.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf
        - asset: assets/fonts/Fredoka-Bold.ttf
