name: lazy_fit
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  resize: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.6.1
  flutter_svg: ^1.1.1+1
  flutter_secure_storage: ^6.0.0
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.1.1
  go_router: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/buttons/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Light.ttf
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Medium.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf
        - asset: assets/fonts/Fredoka-Bold.ttf
